### ISSUE TITLE
Autoconfig: bug in Integer/Double parsing

### ISSUE THREAD

**Issue by rmartinsanta** [rmartinsanta/mork#107]
```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstr>
        at es.urjc.etsii.grafo.autoconfig.factories.GraspConstructiveFactory.initBuilder(GraspConstructiveFactory.java:21)
        at es.urjc.etsii.grafo.autoconfig.factories.GRGraspConstructiveFactory.buildComponent(GRGraspConstructiveFactory.java:11)
        at es.urjc.etsii.grafo.autoconfig.service.AlgorithmBuilderService.buildAlgorithmComponentByName(AlgorithmBuilderService.java:49)
        at es.urjc.etsii.grafo.autoconfig.AlgorithmBuilderListener.exitComponent(AlgorithmBuilderListener.java:34)
        at es.urjc.etsii.grafo.autoconfig.antlr.AlgorithmParser$ComponentContext.exitRule(AlgorithmParser.java:158)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:62)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:38)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
        at es.urjc.etsii.grafo.autoconfig.service.AlgorithmBuilderService.buildAlgorithmComponentFromString(AlgorithmBuilderService.java:85)
        at es.urjc.etsii.grafo.autoconfig.service.AlgorithmBuilderService.buildAlgorithmFromString(AlgorithmBuilderService.java:68)
        at es.urjc.etsii.grafo.autoconfig.irace.AutomaticAlgorithmBuilder.buildFromStringDescription(AutomaticAlgorithmBuilder.java:53)
```

**Comment by rmartinsanta** [comment]
Fixed in c94ca8186070e3ec9808a5cab994406324b44e87
