### ISSUE TITLE
Bug parell irace with randoms

### ISSUE THREAD

**Issue by scaverod** [rmartinsanta/mork#63]
Trace:

```
15:20:57] INFO e.u.e.g.s.i.r.RLangRunner  : # Executing targetRunner ( 2 times)...
[15:20:57] INFO e.u.e.g.s.i.r.RLangRunner  : # 2022-02-14 15:20:57 UTC: /home/sergiocavero/2DIBMP/middleware.sh testConfig1 13 1234567 /home/sergiocavero/2DIBMP/instances/regular/cycle15.mtx   constructive=all random=1 w1=0.8199 penalizeEdges=0 InitialInputVertex=rnd InitialHostVertex=mid localsearch=tamed localSearchStrategy=best maxIter=100 maxWIter=0.75
[15:20:57] INFO e.u.e.g.s.i.r.RLangRunner  : # 2022-02-14 15:20:57 UTC: /home/sergiocavero/2DIBMP/middleware.sh testConfig2 13 1234567 /home/sergiocavero/2DIBMP/instances/regular/cycle15.mtx   constructive=adj random=1 w1=0.7298 penalizeEdges=1 InitialInputVertex=maxG InitialHostVertex=rnd localsearch=tamed localSearchStrategy=best maxIter=100 maxWIter=0.5
[15:20:58] INFO o.a.c.c.C.[.[.[/]          : Initializing Spring DispatcherServlet 'dispatcherServlet'
[15:20:58] INFO o.s.w.s.DispatcherServlet  : Initializing Servlet 'dispatcherServlet'
[15:20:58] INFO o.s.w.s.DispatcherServlet  : Completed initialization in 15 ms
[15:23:06] INFO ebSocketMessageBrokerStats : WebSocketSession[0 current WS(0)-HttpStream(0)-HttpPoll(0), 0 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(0)-CONNECTED(0)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], outboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], sockJsScheduler[pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
[15:23:44] ERROR .[.[.[.[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: ] with root cause

java.lang.IllegalStateException: 
	at es.urjc.etsii.grafo.util.random.RandomManager.lambda$reinitialize$0(RandomManager.java:74) ~[mork-0.10.jar!/:0.10]
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305) ~[na:na]
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195) ~[na:na]
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172) ~[na:na]
	at es.urjc.etsii.grafo.util.random.RandomManager.getRandom(RandomManager.java:36) ~[mork-0.10.jar!/:0.10]
	at es.urjc.etsii.grafo.TDBIMP.constructives.TDBMPAbstractFOConstructive.construct(TDBMPAbstractFOConstructive.java:84) ~[classes!/:0.1-SNAPSHOT]
	at es.urjc.etsii.grafo.TDBIMP.constructives.TDBMPAbstractFOConstructive.construct(TDBMPAbstractFOConstructive.java:22) ~[classes!/:0.1-SNAPSHOT]
	at es.urjc.etsii.grafo.solver.algorithms.SimpleAlgorithm.algorithm(SimpleAlgorithm.java:68) ~[mork-0.10.jar!/:0.10]
	at es.urjc.etsii.grafo.solver.algorithms.multistart.MultiStartAlgorithm.algorithm(MultiStartAlgorithm.java:127) ~[mork-0.10.jar!/:0.10]
	at es.urjc.etsii.grafo.solver.irace.IraceOrchestrator.singleExecution(IraceOrchestrator.java:179) ~[mork-0.10.jar!/:0.10]
	at es.urjc.etsii.grafo.solver.irace.IraceOrchestrator.iraceCallback(IraceOrchestrator.java:148) ~[mork-0.10.jar!/:0.10]
	at es.urjc.etsii.grafo.restcontroller.ExecutionController.execute(ExecutionController.java:50) ~[mork-0.10.jar!/:0.10]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
```

Scenario: 

```
###################################################### -*- mode: r -*- #####
## Scenario setup for Iterated Race (iRace).
############################################################################

## To use the default value of a parameter of iRace, simply do not set
## the parameter (comment it out in this file, and do not give any
## value on the command line).

## File that contains the description of the parameters.
parameterFile = "./parameters.txt"

## Directory where the programs will be run.
execDir = "./"

## File to save tuning results as an R dataset, either absolute path
## or relative to execDir.
# logFile = "./irace.Rdata"

## Directory where tuning instances are located, either absolute path or
## relative to current directory.
trainInstancesDir = "./instances/regular/"

## File with a list of instances and (optionally) parameters.
## If empty or NULL, do not use a file.
#trainInstancesFile = "./training.txt"
#testInstancesFile = "./test.txt"


## A file containing a list of initial configurations.
## If empty or NULL, do not use a file.
# configurationsFile = ""

## The script called for each configuration that launches the program to be
## tuned.  See templates/target-runner.tmpl
targetRunner = "./middleware.sh"

## Number of times to retry a call to target-runner if the call failed.
# targetRunnerRetries = 0

## Optional data passed to targetRunner. This is ignored by the default
## targetRunner function, but it may be used by custom targetRunner functions
## to pass persistent data around.
# targetRunnerData = NULL

## Optional R function to provide custom parallelization of target.runner.  The
## signature of this function should be 'function(experiments, target.runner,
## scenario)', where target.runner is an R function, 'experiments' is a list
## such that each of its elements will be the argument to one call of
## target.runner, and scenario will also be passed to every call. See
## help(target.runner.default) for details.
# targetRunnerParallel = NULL

## Optional script that provides a numeric value for each configuration.
## See templates/target-evaluator.tmpl
# targetEvaluator = ""

## The maximum number of runs (invocations of targetRunner) that will
## performed. It determines the (maximum) budget of experiments for the tuning.
maxExperiments = 100000

## Directory where testing instances are located, either absolute or relative
## to current directory.
# testInstancesDir = ""

## File containing a list of test instances and optionally additional
## parameters for them.  If empty or NULL, do not use a file.
# testInstancesFile = ""

## Number of elite configurations returned by irace that will be tested.
# testNbElites = 1

## Enable/disable testing the elite configurations found at each iteration.
# testIterationElites = 0

## Indicates the number of decimal places to be considered for the
## real parameters.
digits = 4

## A value of 0 silences all debug messages. Higher values provide
## more verbose debug messages.
# debugLevel = 0

## Number of iterations of Race. Do not use something else than the
## default (that is, the dynamic value) unless you know exactly what
## you are doing.
# nbIterations = 0

## Number of experiments per iteration. Do no use something else than
## the default (that is, the dynamic value) unless you know exactly
## what you are doing.
# nbExperimentsPerIteration = 0

## Sample the instances or take them always in the same order.
# sampleInstances = 1

## Specifies the statistical test type: F-test or t-test.
# testType = "F-test"

## Specifies how many instances are seen before the first elimination
## test. It must be a multiple of eachTest.
firstTest = 7

## Specifies how many instances are seen between elimination tests.
# eachTest = 1

## Specifies how many instances are seen between elimination tests.
# eachTest = 1

## The minimum number of configurations that should survive to continue one
## iteration. Do not use something else than the default (that is, the
## dynamic value) unless you know exactly what you are doing.
# minNbSurvival = 0

## The number of configurations that should be sampled and evaluated at
## each iteration. Do no use something else than
## the default (that is, the dynamic value) unless you know exactly
## what you are doing.
# nbConfigurations = 0

## This value is used to determine the number of configurations
## to be sampled and evaluated at each iteration. Use
## the default unless you know exactly what you are doing.
# mu = 5

## Enable/disable deterministic algorithm mode, if enabled irace
## will not use an instance more that once in each race. Note that
## if the number of instances provided is less than firstTest, no
## statistical test will be performed.
# deterministic = 0

## Seed of the random number generator (must be a positive integer, NA
## means use a random seed).
# seed = NA

## Number of calls to targetRunner to execute in parallel. Less than 2
## means calls to targetRunner are sequentially executed.
parallel = 30

## Enable/disable load-balancing when executing experiments in
## parallel. Load-balancing makes better use of computing resources, but
## increases communication overhead. If this overhead is large, disabling
## load-balancing may be faster.
# loadBalancing = 1

## Enable/disable SGE cluster mode. Use qstat to wait for
## cluster jobs to finish (targetRunner must invoke qsub).
# sgeCluster = 0

## Enable/disable MPI. Use MPI to execute targetRunner in parallel
## (parameter parallel is the number of slaves).
# mpi = 0

## Enable/disable the soft restart strategy that avoids premature convergence
## of the probabilistic model.
# softRestart = 1

## Confidence level for the elimination test.
# confidence = 0.95

## Previously saved log file to recover the execution of irace, either
## absolute path or relative to the current directory. If empty or
## NULL, recovery is not performed.
# recoveryFile = ""

## File containing a list of logical expressions that cannot be true
## for any evaluated configuration. If empty or NULL, do not use a file.
forbiddenFile = "./forbidden.txt"

## Enable/disable elitist irace.
# elitist = 1

## Number of instances to add to execution list before previous instances in
## elitist irace.
# elitistNewInstances  = 1

## Limit for the elitist race, number of statistical test performed without
## elimination of configurations.
# elitistLimit  = 2

## END of scenario file
############################################################################
```

**Comment by rmartinsanta** [comment]
Verified, pending other changes, will be fixed soon.
